### PR TITLE
allow content filtering based on header "key" prop

### LINKED ISSUE #191: [Svelte] Table does not consider key property
**Describe the bug**
It seems like the order of the headers matters and that the respective key property is not used to select the cells. See the following snippet to illustrate the problem.

**To Reproduce**
Here an example snippet
```
<main>
<Table {...data} />
</main>
<script>
    import 'agnostic-svelte/css/common.min.css';
    import { Button, Table, Loader, Alert } from 'agnostic-svelte';
    let data = {
        rows: [
            {"score": 10, "team_name": "my team"},
            {"score": 20, "team_name": "my team 2"},
        ],
        headers: [
            {
                label: 'Team',
                key: 'team_name',
                width: 'auto',
                sortable: true,
            },
            {
                label: 'Score',
                key: 'score',
                width: 'auto',
                sortable: true,
            }
        ],
    }
</script>
```

This results in the following table:
| Team | Score |
|---------|----------|
| 10      | my team |
| 20      | my team 2|

**Expected behavior**
The snippet should result in 
| Team | Score |
|---------|----------|
| my team | 10 |
| my team 2 | 20 |

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Firefox
 - Version 98

### PR DESCRIPTION
**Pull request by Croug**
## Description

This PR adds a filterByKey flag for the Table component which allows columns to be re-arranged or even hidden based on the headers "key" property and order.

Fixes #191 

## Checklist:

Please delete options that are not relevant.

- [x] Is this a new feature
- [x] Have you submitted new feature or bugfix issue? Unless it's a small bugix, we generally prefer to track PRs against an issue which starts a dialogue to give us context.
- [x] Tests passing?
- [ ] Have you updated the docs? These live in [site/docs](https://github.com/AgnosticUI/agnosticui/tree/master/site/docs)

### CODE REVIEW

**Comment by Croug** [comment]
This PR is still a work in progress, I'll comment when it's ready to be merged

**Comment by roblevintennis** [comment]
Nice 👍🏽 reading from phone. Can you use the convert to draft mode for these so if doesn't get accidentally merged? When it's ready you can then convert back via the Ready for Review button at the bottom

**Comment by Croug** [comment]
Ok cool, still new to the whole pull request process, didn't know that was an option!

**Comment by Croug** [comment]
Added the storybook test, this is ready to be merged

**Pull request merged**
