### PR TITLE
Fix pagination component reactivity

### PR DESCRIPTION
**Pull request by ocolefed**
## Description

This allows the pagination component to also dynamically change in response to the total number of pages changing.

Fixes # (issue)
#236 

## Checklist:

- [ x ] Is this a bug fix
- [ x ] Have you submitted new feature or bugfix issue? Unless it's a small bugix, we generally prefer to track PRs against an issue which starts a dialogue to give us context.

### CODE REVIEW

**Comment by Croug** [comment]
Good catch! However with this new change if the total is less than the current page it could result in undefined behavior, if you're up to it could you add some guards in there to make sure that `currentPage` is always less than the total? Otherwise I can do it when I get home. Thanks!

**Comment by roblevintennis** [comment]
@ocolefed welcome and thanks for contributing! 💪 🚀 

I think @Croug has an interesting point! 🤔 Do y'all think maybe we should do this in the `useGenerator` helper itself?  That's [here](https://github.com/AgnosticUI/agnosticui/blob/master/agnostic-helpers/src/usePagination.ts) if so.


That way, all frameworks could benefit and stay simpler and the guard would be encapsulated to one place.

**Comment by Croug** [comment]
While I think that would be useful to have for the other frameworks, svelte would still need a bit of love because `currentPage` would still read an incorrect number until you interacted with pagination and we use bind to replicate out `currentPage` changes so at best we're displaying some incorrect information to the user and at worst it'll cause a corrupted state.

**Comment by roblevintennis** [comment]
@Croug thanks for clarification 👍 @ocolefed can you add said guard on this PR?

**Comment by roblevintennis** [comment]
Thanks @ocolefed 🙏🏽

I'm wondering if we should reassign current to total (err on side of fault tolerance but possibly mask bugs in the consumer code)? Or, do that plus warn. Or, just throw an error with a descriptive message so they can correct their code. Cc @Croug too.

Thanks I'd like to hear y'all thoughts

**Comment by Croug** [comment]
I think it's a good idea to set current to total only when current>total. And a warning should be thrown in the console on this occurrence

**Comment by roblevintennis** [comment]
@ocolefed sorry for back and forth -- do you mind just adding a `console.warn` per the discussion above. I think we'll be good to merge after that...thanks in advance!

**Comment by ocolefed** [comment]
No problem @roblevintennis , back and forth is how OSS works :stuck_out_tongue: 

I've added the warning message now, I'm not 100% on the text but I wasn't able to find many other similar examples in the codebase.

**Comment by ocolefed** [comment]
Ahh! Whoops, the classic difference between "save" and "save without formatting" has caught me again. I'll revert those changes and include just the _actual_ changes I meant to introduce

**Comment by roblevintennis** [comment]
Thanks @ocolefed 💯 🚀

**Pull request merged**
