### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by longrunningprocess**
# Pull Request Template

## Description

I noticed `dist` was in the instructions which is not the correct directory at this time.

## Checklist:

Please delete options that are not relevant.

- [ ] Have you updated the docs? These live in [site/docs](https://github.com/AgnosticUI/agnosticui/tree/master/site/docs)

### CODE REVIEW

**Review by roblevintennis — COMMENTED** [review]
I'm sorry for the typo. Thanks for offering the patch!

Are you using Svelte package I'm guessing?

I completely overhauled the svelte package a few weeks ago porting to svelte-kit and when I did so I also moved the common CSS to /css and now it's diverging from the other frameworks like React, Vue etc. which I think are still in /dist -- I'd like to double check this once I'm back on a proper computer (checking from phone). Obviously if they are divergent this change would mislead those users. Bear with me and apologies for the confusing documentation :(

**Comment by roblevintennis** [comment]
Created https://github.com/AgnosticUI/agnosticui/issues/111 to track this and it mentions likely solution we should use here. Again, away from proper machine atm--need to verify

**Comment by longrunningprocess** [comment]
> I'm sorry for the typo. Thanks for offering the patch!
> 
> Are you using Svelte package I'm guessing?
> 
> I completely overhauled the svelte package a few weeks ago porting to svelte-kit and when I did so I also moved the common CSS to /css and now it's diverging from the other frameworks like React, Vue etc. which I think are still in /dist -- I'd like to double check this once I'm back on a proper computer (checking from phone). Obviously if they are divergent this change would mislead those users. Bear with me and apologies for the confusing documentation :(

oh gosh yes, I am using the Svelte package, obviously I assumed you were in my head, sorry about that!

No need to apologize, you're doing some great work here and I really admire some of the design decisions you've made.  I know you're going to save a lot of people a lot of time 🏆

**Comment by longrunningprocess** [comment]
please feel free to close this now that you're tracking it if you don't want the overhead of this one since it's such a simple update.

**Comment by roblevintennis** [comment]
Thanks @longrunningprocess you're input was very tremendously helpful and I even found a second related bug for the React package and a third bug as `agnostic-css` isn't really what I want to express to folks really (`agnostic-FRAMEWORK` is; as each framework distributes the `common.*` css files so there's no need to `npm install agnostic-css` really).

I've updated and published these updates to the docs and now have sections idiomatic for each of the framework implementations:
http://www.agnosticui.com/docs/advanced/advanced-usage.html#modular-css-imports

Thanks for your kind words @longrunningprocess and for your patience as  the docs become more stable and accurate 😃

**Pull request closed without merging**
